### ISSUE TITLE
Fetch the list of podcasts from an actual yaml file

### ISSUE THREAD

**Issue by godsakani** [osscameroon/podcasts#35]
The list of podcasts should be fetched from a `res/podcasts.yaml` file, that is described as follow:

```yaml
- title: "My title"
   description: "The description the podcasts"
   speakers:
     - elhmn
     - elroy
   path: "./tracks/flutervsreactnative.mp3"
   #time in seconds
   duration: 600

- title: "My title 2"
   description: "The description the podcasts 2"
   speakers:
     - sanix
     - goddy
   path: "./tracks/second_podcasts.mp3"
   #time in seconds
   duration: 600
```
